worlds:
  world:
    CanRain: true
    CanIceForm: true
    CanIceMelt: true
    MaxRainTime: 1200
    MaxSunTime: 21600
    MinimumSunTime: 1200
    MinimumRainTime: 60
    CanSnowForm: true
    CanSnowMelt: true
    ThunderstormChancePercentage: 20
    SuperchargedThunderChance: 0.0
    SuperchargedExplosionRadius: 3.0
  world_nether:
    CanRain: true
    CanIceForm: true
    CanIceMelt: true
    MaxRainTime: 1200
    MaxSunTime: 21600
    MinimumSunTime: 1200
    MinimumRainTime: 60
    CanSnowForm: true
    CanSnowMelt: true
    ThunderstormChancePercentage: 20
    SuperchargedThunderChance: 0.0
    SuperchargedExplosionRadius: 3.0
  world_the_end:
    CanRain: true
    CanIceForm: true
    CanIceMelt: true
    MaxRainTime: 1200
    MaxSunTime: 21600
    MinimumSunTime: 1200
    MinimumRainTime: 60
    CanSnowForm: true
    CanSnowMelt: true
    ThunderstormChancePercentage: 20
    SuperchargedThunderChance: 0.0
    SuperchargedExplosionRadius: 3.0
